# Generated by Django 4.1.4 on 2023-03-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='URL')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='athlete/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('sport', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='athlete.athletesport', verbose_name='Вид спорта')),
            ],
        ),
    ]
