# Generated by Django 4.1.4 on 2023-04-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
